# Change these first
owner: avaleriani # Your GitHub username
repo: sticker-printer # Your Github repository name

# Add your sites here
sites:
  - name: Sticker Printer App
    url: https://sticker.observer/
  - name: Sticker Cut Service
    url: https://cut.sticker.observer/
    expectedStatusCodes:
      - 400
  - name: Sticker Queue Service
    url: https://service.sticker.observer/
  - name: Google check
    url: https://google.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  baseUrl: /sticker-uptime-monitor # where "repo" is your repository name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Sticker Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is the status for sticker observer website
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/20 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
